### ISSUE TITLE
problem in getting the PTR value 

### ISSUE THREAD

**Issue by liyun831229** [christophertbrown/iRep#10]
Hi,
I am trying to use iRep in my dataset. However, the PTR value returned is N/A. Is there any problem from the command I am using?
1. I first generate the indexed reference using bowtie2
_bowtie2-build GCF_000253395.1_ASM25339v1_genomic.fna ref_index_

2. run bowtie2 assembly:
_bowtie2 –x ref_index -1 r1.fastq -2 r2.fastq --reorder –S PE.sam_

3. run bPTR
_bPTR -f GCF_000253395.1_ASM25339v1_genomic.fna -s PE.sam -o test.tsv -plot test.pdf -m coverage -ff_

**Comment by christophertbrown** [comment]
Hello,

There are several reasons why it may not be possible to determine an accurate PTR value. In these cases, 'n/a' is reported instead of a value. Usually this is due to low coverage. 

I may be able to identify the cause if you send me your output. 

Best,

Chris
