### ISSUE TITLE
No results, numpy RuntimeWarning

### ISSUE THREAD

**Issue by wrshoemaker** [christophertbrown/iRep#13]
Hello, 

I really liked iRep and have used it before. I re-installed it a few weeks ago got some weird results that I think might be caused by numpy code in the iRep package. 

When I run iRep on my sorted sam file I get the following [output](https://github.com/christophertbrown/iRep/files/1323147/test.iRep.pdf) and the following numpy warnings:

`~/iRep/lib/python3.6/site-packages/numpy/lib/function_base.py:1110: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)`

and

`~/iRep/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)`

I think this might have something to do with the sliding window calculation. Have you seen something similar and do you know how to work around it?

**Comment by christophertbrown** [comment]
Hi Will,

Did you do this test using the same SAM file that you had used previously? From the error and the output it looks like there is an issue with the mapping - the genome you are using has zero coverage. 

Chris

**Comment by wrshoemaker** [comment]
Hi Chris,

I'm not using the same SAM file, but this SAM file has an average coverage of ~500. I also sorted it using the `samtools sort` command and checked to make sure that the reference sequence names in the SAM file match the sequence names in the FASTA file.

**Comment by wrshoemaker** [comment]
I can send a portion of the SAM file if that would be useful. The entire file is ~ 7 gb.

**Comment by christophertbrown** [comment]
Hi Will,

Interesting. Can you please confirm that the read mapping was done in paired-end mode (e.g. using -1 and -2 with Bowtie2)?

Other than that, I'm not sure what the issue could be. It would be helpful if you could send the first few lines of your SAM mapping file.

Sorry for the inconvenience.

Chris

**Comment by wrshoemaker** [comment]
Hi Chris,

I mapped the reads to the reference using `breseq`, which treats the reads of single-end. I wasn't aware that the reads needed to be paired-end. I'll re-map the reads to the reference, re-run `iRep`, and see if there's still a problem.

Thanks for your help,
Will

**Comment by christophertbrown** [comment]
Hi Will,

Hopefully that will fix it for you.

iRep does look at paired read mappings to make sure that both reads in each pair are accurately mapped to the genome. This makes it much less likely to have off target read mappings that could inflate coverage values over some parts of the gnome, and skew results. 

Chris

**Comment by wrshoemaker** [comment]
Thanks Chris,

That solved the problem. Glad to know there's that extra step in iRep. I'll go ahead and close this "issue".
