### ISSUE TITLE
bPTR - ImportError for 'iRep.gc_skew'

### ISSUE THREAD

**Issue by gerners** [christophertbrown/iRep#18]
Hi,

When installing the current iRep version 1.1.9 both via pip or pip and setup.py, bPTR dies with the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/bPTR", line 32, in <module>
    from iRep.gc_skew import gc_skew as gc_skew
ImportError: No module named 'iRep.gc_skew'
```

The iRep executable itself as well as the gc_skew executable work fine and without any errors. Could there be a missing file for the installation or something similar?

Best,
Samuel

**Comment by christophertbrown** [comment]
Hi Samuel,

Sorry about this error.

This should be resolved in the latest version of iRep on GitHub and PyPi. 

You should be able to run `pip install iRep --upgrade` to get the latest version with the fix. Should be iRep-1.1.12.

Let me know if you are still having any problems. 

Chris

**Comment by gerners** [comment]
All working now, thanks!

Best,
Samuel
