### ISSUE TITLE
sam files with spaces in sequence IDs

### ISSUE THREAD

**Issue by ianpgm** [christophertbrown/iRep#2]
I was getting the following error when trying to run this program:

```
# parsing mapping files
Traceback (most recent call last):
  File "./iRep.py", line 966, in <module>
    thresholds, args['t'])
  File "./iRep.py", line 786, in iRep
    genomes = calc_coverage(genomes, mappings, id2g)
  File "./iRep.py", line 157, in calc_coverage
    for read in reads:
  File "./iRep.py", line 879, in filter_mapping
    'both', sort_sam, False, False, sbuffer):
  File "/iRep/bin/mapped.py", line 180, in get_reads
    for read in reads_from_mapping(mapping, contigs, mismatches, mm_option, req_map, region):
  File "/iRep/bin/mapped.py", line 125, in reads_from_mapping
    if int(line[1]) <= 20: # is this from a single read?
ValueError: invalid literal for int() with base 10: '1:N:0:TAAGGCGATAGATCGC'
```

It looked like it was because the ID field in my sam files had a space and therefore wasn't being parsed correctly by mapped.py. I managed to fix this by modifying line 113 of mapped.py to split based on tabs rather than spaces:
`line = line.strip().split("\t")`

That shouldn't mess anything else up, should it?

**Comment by christophertbrown** [comment]
Hey Ian,

That should be fine!

I will add that change to my next update, which I will hopefully release in the next few days. That update will also include a correction for GC sequencing bias, which is an issue with some sequencing libraries. Just FYI, it is probably worth checking out.

Thanks for the info on mapped.py!

Chris
