### ISSUE TITLE
bPTR output shows no coverage and calculated PTR

### ISSUE THREAD

**Issue by sv1714** [christophertbrown/iRep#23]
Hi!
I've been trying to use bPTR but when I run it I get this error.

This is the code I run: bPTR -f sequence.fna -s barcode132_clonal_sort.sam -o test.bPTR.tsv -plot test.bPTR.pdf -m coverage

And this is the warning it gives me:
/Users/sv/anaconda2/envs/iRep/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py:1044: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.rfftn_numpy(a, s, axes)
/Users/sv/anaconda2/envs/iRep/lib/python3.6/site-packages/mkl_fft/_numpy_fft.py:1044: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  output = mkl_fft.rfftn_numpy(a, s, axes)

It still gives me an output but it's missing the coverage and consensus Ori and Ter.  
[test.bPTR.pdf](https://github.com/christophertbrown/iRep/files/2268011/test.bPTR.pdf)

Any help would be much appreciated. Thanks!

**Comment by christophertbrown** [comment]
Hi,

Not sure about this. Could there be an issue with the reads and/or mapping that would result in no coverage? Are the reads paired and do they map accurately to the genome (i.e. without mismatches)?

Chris

**Comment by sv1714** [comment]
Hello,

Sorry forgot to close this, I think this is because I was using the output of breseq which doesn't align as paired reads so I've had to redo my alignment with bowtie2.

Thanks Chris!

**Comment by christophertbrown** [comment]
Not aligning as paired reads would definitely be a problem. Thanks for the update! Hopefully re-mapping with Bowtie2 will solve the problem.
