### ISSUE TITLE
A irep figure from my sample

### ISSUE THREAD

**Issue by Anqi-Dai** [christophertbrown/iRep#38]
<img width="608" alt="Screen Shot 2021-11-02 at 11 30 57 AM" src="https://user-images.githubusercontent.com/29258219/139878293-347c9b6e-4ad4-4b22-aa6f-c3680cdf991b.png">
Hi Christopher, does the above figure look correct? It is not as clean as your example figure, and I wonder if this validates the calculation for irep.
Thank you
Angel

**Comment by christophertbrown** [comment]
Hi Angel,

I agree that it is not as clean looking, and the iRep value is suspiciously high. Although the curve fit does look good, the large shift in coverage is suspicious. In your previous email you said you were using a complete genome for the analysis, is that still true or have you switched to using a draft genome from a metagenome assembly? Either way, it might be helpful to look at the attached plot for your sample to determine if there may be some contamination in the genome - usually this can be seen as distinct clusters in the gc vs coverage plot. 

Apologies for not being able to respond to your questions back in February. Please feel free to reach out if you have any other questions about the methods. 

Best,

Chris

**Comment by Anqi-Dai** [comment]
Hi Chris, thank you very much for your quick reply

The GC vs coverage plot is here:
<img width="698" alt="Screen Shot 2021-11-02 at 12 56 19 PM" src="https://user-images.githubusercontent.com/29258219/139910698-93b28552-67f9-4cbc-a59f-5311e8802d30.png">
Does this look like contamination?

Angel

**Comment by Anqi-Dai** [comment]
Hi @christophertbrown How is the draft genome defined? Does it represent the MAG that built from bins of contigs?
Piece the contigs within a bin together to make a circular genome and this is a draft genome?

Angel

**Comment by christophertbrown** [comment]
Hi Angel,

Yes, by draft genome I just meant the MAG. Please note the quality requirements in the README, and included below for reference. They do not need to be concatenated. 

> iRep requires high-quality draft genomes (>=75% complete, <=175 fragments/Mbp sequence, and <=2% contamination). iRep will only make use of scaffolds ≥5 Kbp in length, thus it is important to make sure that estimates of genome completion are calculated based on scaffolds that pass this threshold.


Chris

**Comment by christophertbrown** [comment]
Hi Angel,

Thank you for sharing. There are some contigs/fragments outside of the average GC range, but they are not of unusually high or low coverage, so I would not think that would make much of a difference. No serious signs of contamination here, in my opinion. 

Best,

Chris

**Comment by Anqi-Dai** [comment]
Hi Chris,
Thank you very much for your reply. If I filter by the contamination less than 2%, this irep > 4 bin is gone, since it has a contamination of 6%. I know you said it doesn't look like serious contamination, but I've decided to stick your rules. Again, thanks for the info!

Angel

**Comment by christophertbrown** [comment]
Hi Angel,

Good idea to filter it out given the estimated contamination. Thanks for the update! 

Best,

Chris
