### ISSUE TITLE
 iRep requires

### ISSUE THREAD

**Issue by maocheng2020** [christophertbrown/iRep#39]
iRep requires high-quality draft genomes (>=75% complete, <=175 fragments/Mbp sequence, and <=2% contamination).But when I use checkm to calculate the assembly genome with a completeness of 60, I wonder why there are still results instead of NA? Should I first select an assembled genome that meets the requirements before calculating?There are too few assembled genomes that can fit <=2% contamination. Thanks!

**Comment by christophertbrown** [comment]
It is important to follow the guidelines for genome quality in order to be able to trust the results from iRep. We benchmarked these factors in the manuscript and found that going beyond the recommendations can result in skewed results. 

Best,

Chris

**Comment by maocheng2020** [comment]
Thanks your for your reply. I'll filter out the draft genomes(<75% complete or >2% contamination) before run iRep.

**Comment by maocheng2020** [comment]
@christophertbrown Hi. When I follow the guidelines of genome quality  to calculate my data, I found that irep has values greater than 2.  Your manuscript had described that "An iRep value of 1.25 would indicate that, on average, only one quarter of the cells are replicating" . My understanding is that irep values are in the range 1 to 2, right? How should I interpret values greater than 2? Thanks for the tools you developed.

![551](https://user-images.githubusercontent.com/75960648/163776200-fa943aef-a494-4fdc-ae7a-6f1f54104dcd.png)
![552](https://user-images.githubusercontent.com/75960648/163776206-07750e0e-e515-4c44-bb0c-b4980ddd7111.png)
![553](https://user-images.githubusercontent.com/75960648/163776210-0ef6c616-0c4a-487e-8850-1052e304fbf5.png)

**Comment by Anto007** [comment]
Not the developer of this tool but as a fellow user, my understanding is that iRep values > 2 are made possible by the occurrence of multiple replication forks at origin. Hope this info helps.

**Comment by christophertbrown** [comment]
Thanks for the response, Anto007! That is indeed exactly how I would explain this result.

Maocheng2020 - the data looks good to me. Although coverage is somewhat low the distribution and fit are clean. 

Best,

Chris
