### ISSUE TITLE
cPickle

### ISSUE THREAD

**Issue by mocat2** [christophertbrown/iRep#4]
Hi

I am installing the dependencies. cPickle is listed as one. I've read this: http://stackoverflow.com/questions/37132899/installing-cpickle-with-python-3-5

"However, in 3.x, it's easier just to use pickle. No need to install anything. If something requires cPickle in python 3.x, then that's probably a bug."

Could you please comment whether cPickle is a requirement?

**Comment by christophertbrown** [comment]
Hi,

cPickle is not required. I forgot to remove it from the list of dependencies after converting from python 2.7 to 3.

I just updated the docs. 

Let me know if you run into trouble. 

Chris
