### ISSUE TITLE
error with GC_skew

### ISSUE THREAD

**Issue by BJCampbelllab** [christophertbrown/iRep#9]
Hi-
I'm new to iRep, but am really eager to use it and see my results!  I get this error when I run gc_skew:
-bash-4.2$ gc_skew -f CB_Spr15_L08_bin.56.fa 
  File "/usr/bin/gc_skew", line 49
    print('%s: Too Short' % (name), file=sys.stderr)
                                        ^
SyntaxError: invalid syntax

Any help/suggestions would be appreciated!

**Comment by BJCampbelllab** [comment]
Okay, I see that the program needs matlab.  I don't have it (it is expensive, I believe).  Any workaround for that?

**Comment by christophertbrown** [comment]
Hi,

iRep does not require Matlab or any software that needs to be purchased. It looks to me like you were trying to run gc_skew with python 2.7 instead of python 3. I recommend using pyenv to install python 3 and to manage different python versions. 

Hope this helps!

Chris

**Comment by BJCampbelllab** [comment]
Thanks! I'll let you know if I have any more issues.

Sent from my iPhone

On Jun 5, 2017, at 12:56 PM, christophertbrown <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

iRep does not require Matlab or any software that needs to be purchased. It looks to me like you were trying to run gc_skew with python 2.7 instead of python 3. I recommend using pyenv to install python 3 and to manage different python versions.

Hope this helps!

Chris
